#!/home/haruka/.rvm/rubies/ruby-2.3.0/bin/ruby
#require 'rubygems'
#require 'bundler'
#Bundler.setup :default

require 'gli'
require 'trema'
puts "admit command start"
# patch_panel command
module PatchPanelApp
  extend GLI::App

  desc 'Admit Flow_mod'
  arg_name 'dpid password'
  command :admit do |c|
    c.desc 'Location to find socket files'
    c.flag [:S, :socket_dir], default_value: Trema::DEFAULT_SOCKET_DIR

    c.action do |_global_options, options, args|
      dpid = args[0].hex
      id = args[1].to_i
      
      Trema.trema_process('Sim', options[:socket_dir]).controller.
        admit_flow_mod(dpid, id)
    end
  end

  desc 'Cancel Flow_mod'
  arg_name 'dpid password'
  command :cancel do |c|
    c.desc 'Location to find socket files'
    c.flag [:S, :socket_dir], default_value: Trema::DEFAULT_SOCKET_DIR

    c.action do |_global_options, options, args|
      dpid = args[0].hex
      id = args[1].to_i
      
      Trema.trema_process('Sim', options[:socket_dir]).controller.
        cancel_flow_mod(dpid, id)
    end
  end

  exit run(ARGV)
end
