# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'trema' , '0.10.1'
gem 'mysql2'
gem 'google-api-client'
gem 'pry'
#gem 'rbconfig'
gem 'rmail'
gem 'file-utils'
gem 'gli', '2.13.4'
